FROM ros:humble-perception

ENV WS_DIR="/ros2_ws"
WORKDIR ${WS_DIR}

SHELL ["/bin/bash", "-c"]

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get install -y \
    build-essential \
    cmake \
    git-all \
    software-properties-common \
 && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
 && apt-get install -y \
    ros-${ROS_DISTRO}-librealsense2* \
    ros-${ROS_DISTRO}-realsense2-* \
 && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
 && apt-get install -y \
    ros-${ROS_DISTRO}-rviz2 \
 && rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install ros-humble-rtabmap-ros -y

RUN mkdir -p ${WS_DIR}/src

RUN echo 'source /opt/ros/${ROS_DISTRO}/setup.bash && colcon build' > /ros2_ws/build_workspace.sh \
 && chmod +x /ros2_ws/build_workspace.sh

CMD ["bash"]
